// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBYbO_H7gwucF99zi1jWY1LjJesnxYcDgg',
    appId: '1:383406049943:web:45a9ab1bf2254bb968f7d2',
    messagingSenderId: '383406049943',
    projectId: 'pramana-qrverifier',
    authDomain: 'pramana-qrverifier.firebaseapp.com',
    databaseURL: 'https://pramana-qrverifier-default-rtdb.firebaseio.com',
    storageBucket: 'pramana-qrverifier.appspot.com',
    measurementId: 'G-TH9WKE6V3M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBxRsAyX3z_tVpl3iCewCtvzst7hLiqaAw',
    appId: '1:383406049943:android:f75752c66b44c73568f7d2',
    messagingSenderId: '383406049943',
    projectId: 'pramana-qrverifier',
    databaseURL: 'https://pramana-qrverifier-default-rtdb.firebaseio.com',
    storageBucket: 'pramana-qrverifier.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAFUGVZQcUs1nmnjWkcYCLwER3apUxMzzE',
    appId: '1:383406049943:ios:777fcc92e3a84b8d68f7d2',
    messagingSenderId: '383406049943',
    projectId: 'pramana-qrverifier',
    databaseURL: 'https://pramana-qrverifier-default-rtdb.firebaseio.com',
    storageBucket: 'pramana-qrverifier.appspot.com',
    iosBundleId: 'com.pramana.pramanaQrVerifier',
  );
}
